resources:
  repositories:
  - repository: WSO2_APIM_HELM_Deployment
    type: github
    endpoint: github.com_Nareash20010150
    name: Nareash20010150/WSO2_APIM_HELM_Deployment

  - repository: MovieReview
    type: github
    endpoint: github.com_Nareash20010150
    name: Nareash20010150/MovieReview

  - repository: Dating-app 
    endpoint: github.com_Nareash20010150
    type: github
    name: Nareash20010150/Dating-app

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- script: |
    if [ "$(Build.Repository.Name)" != "master_repo" ]; then
          cat "${{ variables['Build.Repository.LocalPath'] }}/README.md"
    else
        echo "Repository is master_repo"
    fi
  displayName: 'Run a multi-line script'
