resources:
  repositories:
    
  - repository: WSO2_APIM_HELM_Deployment
    type: github
    endpoint: github.com_Nareash20010150
    name: Nareash20010150/WSO2_APIM_HELM_Deployment

  - repository: MovieReview
    type: github
    endpoint: github.com_Nareash20010150
    name: Nareash20010150/MovieReview

  - repository: Dating_app
    type: github
    endpoint: github.com_Nareash20010150
    name: Nareash20010150/Dating_app
trigger:
- main
stages:
- stage: CheckoutRepositories
  displayName: 'Checkout Repositories'  
  
  
  
  
  
  
  
  
  
  
  
  
  jobs:
  - job: CheckoutAndPrintReadme_WSO2_APIM_HELM_Deployment
    displayName: "Checkout and Print README WSO2_APIM_HELM_Deployment"
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: WSO2_APIM_HELM_Deployment
    - script: |
        echo "Checking out repository: WSO2_APIM_HELM_Deployment"
        echo "Printing README file for repository: WSO2_APIM_HELM_Deployment"
        cat README.md
        echo '----------------------------------------------'


  - job: CheckoutAndPrintReadme_MovieReview
    displayName: "Checkout and Print README MovieReview"
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: MovieReview
    - script: |
        echo "Checking out repository: MovieReview"
        echo "Printing README file for repository: MovieReview"
        cat README.md
        echo '----------------------------------------------'


  - job: CheckoutAndPrintReadme_Dating_app
    displayName: "Checkout and Print README Dating_app"
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: Dating_app
    - script: |
        echo "Checking out repository: Dating_app"
        echo "Printing README file for repository: Dating_app"
        cat README.md
        echo '----------------------------------------------'

