resources:
  - template: templates/include-repos.yml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: WSO2_APIM_HELM_Deployment
- checkout: MovieReview
- checkout: Dating-app 

- script: |
    env=($(ls --ignore=master_repo))
    for filename in "${env[@]}"; do
      cat $filename/README.md
    done

  displayName: 'Run a multi-line script'